-- Seed Data: 200+ Tasks
-- Requirements: 14.1, 14.2, 14.3, 14.4, 14.5
-- Even distribution across 6 categories with English and Hinglish descriptions

-- LEARN CATEGORY (35 tasks)
INSERT INTO tasks (title, description, category, duration_seconds, tags, difficulty, type) VALUES
('Learn a new word', 'Look up and learn the meaning of one new English word', 'learn', 60, ARRAY['vocabulary', 'language', 'education'], 1, 'learn'),
('Naya shabd seekho', 'Ek naya Hindi ya English word ka matlab samjho', 'learn', 60, ARRAY['vocabulary', 'language', 'hinglish'], 1, 'learn'),
('Read news article', 'Read one short news article about current events', 'learn', 90, ARRAY['reading', 'news', 'current-affairs'], 2, 'learn'),
('Ek article padho', 'Koi bhi interesting topic par ek chhota article padho', 'learn', 90, ARRAY['reading', 'hinglish', 'knowledge'], 2, 'learn'),
('Watch educational video', 'Watch a 2-minute educational video on any topic', 'learn', 120, ARRAY['video', 'education', 'learning'], 1, 'learn'),
('Practice mental math', 'Solve 5 mental math problems without calculator', 'learn', 90, ARRAY['math', 'brain', 'calculation'], 3, 'learn'),
('Mental math karo', 'Calculator ke bina 5 math problems solve karo', 'learn', 90, ARRAY['math', 'brain', 'hinglish'], 3, 'learn'),
('Learn historical fact', 'Research and learn one interesting historical fact', 'learn', 75, ARRAY['history', 'facts', 'knowledge'], 2, 'learn'),
('Science fact seekho', 'Ek interesting science fact ke baare mein padho', 'learn', 75, ARRAY['science', 'facts', 'hinglish'], 2, 'learn'),
('Practice typing', 'Practice typing for 1 minute to improve speed', 'learn', 60, ARRAY['typing', 'skill', 'practice'], 1, 'learn'),
('Learn keyboard shortcut', 'Learn and practice one new keyboard shortcut', 'learn', 45, ARRAY['computer', 'productivity', 'shortcuts'], 1, 'learn'),
('Shortcut yaad karo', 'Ek naya keyboard shortcut seekho aur use karo', 'learn', 45, ARRAY['computer', 'productivity', 'hinglish'], 1, 'learn'),
('Read a poem', 'Read and appreciate one short poem', 'learn', 60, ARRAY['poetry', 'literature', 'reading'], 1, 'learn'),
('Learn about country', 'Learn 3 facts about a country you have never visited', 'learn', 90, ARRAY['geography', 'culture', 'travel'], 2, 'learn'),
('Desh ke baare mein', 'Kisi naye desh ke baare mein 3 facts padho', 'learn', 90, ARRAY['geography', 'culture', 'hinglish'], 2, 'learn'),
('Learn coding concept', 'Learn one basic programming concept or syntax', 'learn', 120, ARRAY['coding', 'programming', 'tech'], 3, 'learn'),
('Practice pronunciation', 'Practice pronouncing 5 difficult words correctly', 'learn', 60, ARRAY['language', 'speaking', 'pronunciation'], 2, 'learn'),
('Learn a quote', 'Read and memorize one inspirational quote', 'learn', 45, ARRAY['quotes', 'inspiration', 'memory'], 1, 'learn'),
('Quote yaad karo', 'Ek motivational quote padho aur yaad karo', 'learn', 45, ARRAY['quotes', 'inspiration', 'hinglish'], 1, 'learn'),
('Study a map', 'Study a map and learn locations of 3 new places', 'learn', 90, ARRAY['geography', 'maps', 'learning'], 2, 'learn'),
('Learn about nutrition', 'Learn nutritional benefits of one food item', 'learn', 75, ARRAY['health', 'nutrition', 'food'], 2, 'learn'),
('Nutrition padho', 'Kisi food item ke health benefits ke baare mein seekho', 'learn', 75, ARRAY['health', 'nutrition', 'hinglish'], 2, 'learn'),
('Learn grammar rule', 'Learn and practice one English grammar rule', 'learn', 90, ARRAY['grammar', 'language', 'english'], 2, 'learn'),
('Read book summary', 'Read a 2-minute summary of a popular book', 'learn', 120, ARRAY['books', 'reading', 'summary'], 2, 'learn'),
('Learn about invention', 'Learn about one important invention and its inventor', 'learn', 90, ARRAY['invention', 'history', 'innovation'], 2, 'learn'),
('Practice memory', 'Memorize a sequence of 10 random numbers', 'learn', 60, ARRAY['memory', 'brain', 'practice'], 3, 'learn'),
('Memory game khelo', '10 random numbers ko yaad karne ki koshish karo', 'learn', 60, ARRAY['memory', 'brain', 'hinglish'], 3, 'learn'),
('Learn life skill', 'Learn one practical life skill tip or hack', 'learn', 75, ARRAY['life-skills', 'practical', 'tips'], 1, 'learn'),
('Study astronomy', 'Learn about one constellation or planet', 'learn', 90, ARRAY['astronomy', 'space', 'science'], 2, 'learn'),
('Learn about wildlife', 'Learn 3 facts about an animal species', 'learn', 75, ARRAY['animals', 'wildlife', 'nature'], 1, 'learn'),
('Janwar ke baare mein', 'Kisi ek animal ke baare mein interesting facts padho', 'learn', 75, ARRAY['animals', 'wildlife', 'hinglish'], 1, 'learn'),
('Practice logic puzzle', 'Solve one simple logic puzzle or riddle', 'learn', 90, ARRAY['logic', 'puzzle', 'brain'], 3, 'learn'),
('Learn about art', 'Learn about one famous painting or artist', 'learn', 90, ARRAY['art', 'culture', 'history'], 2, 'learn'),
('Study economics', 'Learn one basic economics concept', 'learn', 120, ARRAY['economics', 'finance', 'learning'], 3, 'learn'),
('Learn fun fact', 'Learn one interesting random fun fact', 'learn', 45, ARRAY['facts', 'trivia', 'knowledge'], 1, 'learn');

-- MOVE CATEGORY (35 tasks)
INSERT INTO tasks (title, description, category, duration_seconds, tags, difficulty, type) VALUES
('Do 10 jumping jacks', 'Perform 10 jumping jacks with proper form', 'move', 30, ARRAY['cardio', 'exercise', 'quick'], 1, 'move'),
('10 jumping jacks karo', 'Achhe form ke saath 10 jumping jacks complete karo', 'move', 30, ARRAY['cardio', 'exercise', 'hinglish'], 1, 'move'),
('Stretch your arms', 'Do arm stretches for 1 minute', 'move', 60, ARRAY['stretching', 'flexibility', 'arms'], 1, 'move'),
('Walk for 2 minutes', 'Take a quick 2-minute walk around your space', 'move', 120, ARRAY['walking', 'cardio', 'movement'], 1, 'move'),
('2 minute walk karo', 'Apne ghar ya office mein 2 minute walk karo', 'move', 120, ARRAY['walking', 'cardio', 'hinglish'], 1, 'move'),
('Do 5 squats', 'Perform 5 squats with proper form', 'move', 45, ARRAY['strength', 'legs', 'exercise'], 2, 'move'),
('5 squats karo', 'Sahi tarike se 5 squats complete karo', 'move', 45, ARRAY['strength', 'legs', 'hinglish'], 2, 'move'),
('Neck rolls', 'Do gentle neck rolls to release tension', 'move', 45, ARRAY['stretching', 'neck', 'relaxation'], 1, 'move'),
('Shoulder shrugs', 'Do 10 shoulder shrugs to release tension', 'move', 30, ARRAY['shoulders', 'stretching', 'relaxation'], 1, 'move'),
('Kandhe hilao', '10 shoulder shrugs karke tension release karo', 'move', 30, ARRAY['shoulders', 'stretching', 'hinglish'], 1, 'move'),
('Do 10 push-ups', 'Perform 10 push-ups or modified push-ups', 'move', 60, ARRAY['strength', 'arms', 'chest'], 3, 'move'),
('Leg stretches', 'Stretch your legs for 1 minute', 'move', 60, ARRAY['stretching', 'legs', 'flexibility'], 1, 'move'),
('Tang stretch karo', 'Apni legs ko 1 minute ke liye stretch karo', 'move', 60, ARRAY['stretching', 'legs', 'hinglish'], 1, 'move'),
('Do 15 high knees', 'Perform 15 high knees in place', 'move', 45, ARRAY['cardio', 'legs', 'exercise'], 2, 'move'),
('Climb stairs', 'Climb up and down stairs for 1 minute', 'move', 60, ARRAY['cardio', 'legs', 'stairs'], 2, 'move'),
('Seedhi chadhna', '1 minute tak stairs up-down karo', 'move', 60, ARRAY['cardio', 'legs', 'hinglish'], 2, 'move'),
('Do 10 lunges', 'Perform 10 lunges alternating legs', 'move', 60, ARRAY['strength', 'legs', 'balance'], 2, 'move'),
('Wrist circles', 'Do wrist circles to prevent strain', 'move', 30, ARRAY['wrists', 'stretching', 'prevention'], 1, 'move'),
('Kalai ghumao', 'Wrist circles karke strain prevent karo', 'move', 30, ARRAY['wrists', 'stretching', 'hinglish'], 1, 'move'),
('Do 20 toe touches', 'Bend and touch your toes 20 times', 'move', 60, ARRAY['stretching', 'flexibility', 'back'], 2, 'move'),
('Dance for 1 minute', 'Dance freely to your favorite song for 1 minute', 'move', 60, ARRAY['dance', 'fun', 'cardio'], 1, 'move'),
('1 minute dance karo', 'Apne favorite song par 1 minute dance karo', 'move', 60, ARRAY['dance', 'fun', 'hinglish'], 1, 'move'),
('Do 10 sit-ups', 'Perform 10 sit-ups or crunches', 'move', 60, ARRAY['core', 'abs', 'strength'], 3, 'move'),
('Ankle rotations', 'Rotate your ankles 10 times each direction', 'move', 45, ARRAY['ankles', 'stretching', 'mobility'], 1, 'move'),
('Ankle ghumao', 'Dono ankles ko 10 baar har direction mein ghumao', 'move', 45, ARRAY['ankles', 'stretching', 'hinglish'], 1, 'move'),
('Do 10 burpees', 'Perform 10 burpees at your own pace', 'move', 90, ARRAY['cardio', 'full-body', 'intense'], 4, 'move'),
('Side bends', 'Do 10 side bends on each side', 'move', 60, ARRAY['core', 'stretching', 'flexibility'], 2, 'move'),
('Side bend karo', 'Dono sides par 10-10 side bends karo', 'move', 60, ARRAY['core', 'stretching', 'hinglish'], 2, 'move'),
('Do 30 seconds plank', 'Hold a plank position for 30 seconds', 'move', 30, ARRAY['core', 'strength', 'endurance'], 3, 'move'),
('Calf raises', 'Do 20 calf raises', 'move', 45, ARRAY['calves', 'legs', 'strength'], 2, 'move'),
('Calf raise karo', '20 calf raises complete karo', 'move', 45, ARRAY['calves', 'legs', 'hinglish'], 2, 'move'),
('Do arm circles', 'Do 20 arm circles forward and backward', 'move', 60, ARRAY['arms', 'shoulders', 'warm-up'], 1, 'move'),
('March in place', 'March in place for 1 minute', 'move', 60, ARRAY['cardio', 'warm-up', 'movement'], 1, 'move'),
('Spot par march karo', '1 minute tak ek jagah par march karo', 'move', 60, ARRAY['cardio', 'warm-up', 'hinglish'], 1, 'move'),
('Do 10 mountain climbers', 'Perform 10 mountain climbers', 'move', 45, ARRAY['cardio', 'core', 'full-body'], 3, 'move'),
('Hip circles', 'Do 10 hip circles in each direction', 'move', 60, ARRAY['hips', 'mobility', 'stretching'], 1, 'move');

-- REFLECT CATEGORY (35 tasks)
INSERT INTO tasks (title, description, category, duration_seconds, tags, difficulty, type) VALUES
('Gratitude moment', 'Think of 3 things you are grateful for today', 'reflect', 60, ARRAY['gratitude', 'mindfulness', 'positive'], 1, 'reflect'),
('Shukriya karo', 'Aaj ke 3 achhe cheezon ke liye shukriya karo', 'reflect', 60, ARRAY['gratitude', 'mindfulness', 'hinglish'], 1, 'reflect'),
('Deep breathing', 'Take 10 deep breaths slowly and mindfully', 'reflect', 60, ARRAY['breathing', 'calm', 'meditation'], 1, 'reflect'),
('Gehri saans lo', '10 baar gehri saans lo aur relax karo', 'reflect', 60, ARRAY['breathing', 'calm', 'hinglish'], 1, 'reflect'),
('Set daily intention', 'Set one positive intention for the day', 'reflect', 45, ARRAY['intention', 'goals', 'mindfulness'], 1, 'reflect'),
('Review your goals', 'Review one of your personal or professional goals', 'reflect', 90, ARRAY['goals', 'planning', 'reflection'], 2, 'reflect'),
('Apne goals dekho', 'Apne ek goal ko review karo aur plan banao', 'reflect', 90, ARRAY['goals', 'planning', 'hinglish'], 2, 'reflect'),
('Mindful observation', 'Observe your surroundings mindfully for 1 minute', 'reflect', 60, ARRAY['mindfulness', 'awareness', 'present'], 1, 'reflect'),
('Body scan', 'Do a quick body scan to notice any tension', 'reflect', 90, ARRAY['body-awareness', 'relaxation', 'mindfulness'], 2, 'reflect'),
('Body scan karo', 'Apne body mein tension check karo aur relax karo', 'reflect', 90, ARRAY['body-awareness', 'relaxation', 'hinglish'], 2, 'reflect'),
('Positive affirmation', 'Repeat one positive affirmation 5 times', 'reflect', 45, ARRAY['affirmation', 'positive', 'self-talk'], 1, 'reflect'),
('Journal one thought', 'Write down one thought or feeling in a journal', 'reflect', 90, ARRAY['journaling', 'writing', 'emotions'], 2, 'reflect'),
('Ek thought likho', 'Apni diary mein ek thought ya feeling likho', 'reflect', 90, ARRAY['journaling', 'writing', 'hinglish'], 2, 'reflect'),
('Visualize success', 'Visualize yourself succeeding at one task today', 'reflect', 75, ARRAY['visualization', 'success', 'motivation'], 2, 'reflect'),
('Practice self-compassion', 'Be kind to yourself about one mistake or challenge', 'reflect', 60, ARRAY['self-compassion', 'kindness', 'mental-health'], 2, 'reflect'),
('Khud se pyaar karo', 'Apni ek galti ke liye khud ko maaf karo', 'reflect', 60, ARRAY['self-compassion', 'kindness', 'hinglish'], 2, 'reflect'),
('Mindful listening', 'Listen to ambient sounds mindfully for 1 minute', 'reflect', 60, ARRAY['listening', 'mindfulness', 'awareness'], 1, 'reflect'),
('Check your emotions', 'Identify and name your current emotion', 'reflect', 45, ARRAY['emotions', 'awareness', 'mental-health'], 1, 'reflect'),
('Emotion check karo', 'Abhi aap kaisa feel kar rahe ho, identify karo', 'reflect', 45, ARRAY['emotions', 'awareness', 'hinglish'], 1, 'reflect'),
('Reflect on learning', 'Think about one thing you learned recently', 'reflect', 75, ARRAY['learning', 'growth', 'reflection'], 2, 'reflect'),
('Practice acceptance', 'Accept one thing you cannot change right now', 'reflect', 60, ARRAY['acceptance', 'peace', 'mindfulness'], 2, 'reflect'),
('Acceptance practice', 'Ek cheez ko accept karo jo aap change nahi kar sakte', 'reflect', 60, ARRAY['acceptance', 'peace', 'hinglish'], 2, 'reflect'),
('Appreciate yourself', 'Acknowledge one thing you did well today', 'reflect', 45, ARRAY['self-appreciation', 'positive', 'confidence'], 1, 'reflect'),
('Mindful eating moment', 'Eat one bite of food very slowly and mindfully', 'reflect', 60, ARRAY['mindful-eating', 'awareness', 'food'], 1, 'reflect'),
('Dhyan se khao', 'Ek bite ko bahut dhyan se aur slowly khao', 'reflect', 60, ARRAY['mindful-eating', 'awareness', 'hinglish'], 1, 'reflect'),
('Release tension', 'Consciously release tension from your shoulders', 'reflect', 45, ARRAY['relaxation', 'tension-release', 'body'], 1, 'reflect'),
('Reflect on kindness', 'Recall one act of kindness you witnessed or did', 'reflect', 60, ARRAY['kindness', 'compassion', 'reflection'], 1, 'reflect'),
('Kindness yaad karo', 'Kisi ki kindness ya apni kindness yaad karo', 'reflect', 60, ARRAY['kindness', 'compassion', 'hinglish'], 1, 'reflect'),
('Practice patience', 'Reflect on a situation where you can be more patient', 'reflect', 75, ARRAY['patience', 'growth', 'mindfulness'], 2, 'reflect'),
('Smile meditation', 'Smile gently and notice how it affects your mood', 'reflect', 45, ARRAY['smile', 'mood', 'positive'], 1, 'reflect'),
('Muskurao', 'Halke se muskurao aur apne mood ko notice karo', 'reflect', 45, ARRAY['smile', 'mood', 'hinglish'], 1, 'reflect'),
('Reflect on progress', 'Think about progress you have made in any area', 'reflect', 90, ARRAY['progress', 'growth', 'motivation'], 2, 'reflect'),
('Practice letting go', 'Let go of one worry or negative thought', 'reflect', 75, ARRAY['letting-go', 'peace', 'mental-health'], 2, 'reflect'),
('Chinta chhodo', 'Ek worry ya negative thought ko jaane do', 'reflect', 75, ARRAY['letting-go', 'peace', 'hinglish'], 2, 'reflect'),
('Mindful pause', 'Pause and be fully present for 1 minute', 'reflect', 60, ARRAY['mindfulness', 'present', 'awareness'], 1, 'reflect'),
('Connect with values', 'Reflect on one of your core values', 'reflect', 90, ARRAY['values', 'purpose', 'reflection'], 2, 'reflect');

-- FUN CATEGORY (35 tasks)
INSERT INTO tasks (title, description, category, duration_seconds, tags, difficulty, type) VALUES
('Tell a joke', 'Think of or look up one funny joke', 'fun', 45, ARRAY['humor', 'laughter', 'entertainment'], 1, 'fun'),
('Ek joke suno', 'Koi funny joke suno ya yaad karo', 'fun', 45, ARRAY['humor', 'laughter', 'hinglish'], 1, 'fun'),
('Doodle something', 'Draw a quick doodle or sketch', 'fun', 90, ARRAY['drawing', 'creativity', 'art'], 1, 'fun'),
('Kuch draw karo', 'Ek quick doodle ya sketch banao', 'fun', 90, ARRAY['drawing', 'creativity', 'hinglish'], 1, 'fun'),
('Play word game', 'Play a quick word game or make an anagram', 'fun', 60, ARRAY['words', 'games', 'brain'], 2, 'fun'),
('Listen to favorite song', 'Listen to one of your favorite songs', 'fun', 120, ARRAY['music', 'enjoyment', 'mood'], 1, 'fun'),
('Favorite song suno', 'Apna ek favorite song suno aur enjoy karo', 'fun', 120, ARRAY['music', 'enjoyment', 'hinglish'], 1, 'fun'),
('Make funny face', 'Make 5 different funny faces in the mirror', 'fun', 30, ARRAY['humor', 'silly', 'mood'], 1, 'fun'),
('Watch comedy clip', 'Watch a 1-minute comedy video clip', 'fun', 60, ARRAY['comedy', 'laughter', 'video'], 1, 'fun'),
('Comedy clip dekho', '1 minute ki funny video clip dekho', 'fun', 60, ARRAY['comedy', 'laughter', 'hinglish'], 1, 'fun'),
('Play air instrument', 'Play air guitar or air drums for 30 seconds', 'fun', 30, ARRAY['music', 'silly', 'movement'], 1, 'fun'),
('Sing a song', 'Sing one verse of your favorite song', 'fun', 60, ARRAY['singing', 'music', 'expression'], 1, 'fun'),
('Gaana gao', 'Apne favorite song ki ek line gao', 'fun', 60, ARRAY['singing', 'music', 'hinglish'], 1, 'fun'),
('Create a rhyme', 'Make up a silly rhyme about your day', 'fun', 75, ARRAY['creativity', 'words', 'humor'], 2, 'fun'),
('Play thumb war', 'Challenge someone to a quick thumb war', 'fun', 30, ARRAY['game', 'social', 'fun'], 1, 'fun'),
('Thumb war khelo', 'Kisi ke saath thumb war khelo', 'fun', 30, ARRAY['game', 'social', 'hinglish'], 1, 'fun'),
('Do silly walk', 'Walk silly like a cartoon character for 30 seconds', 'fun', 30, ARRAY['silly', 'movement', 'humor'], 1, 'fun'),
('Make up story', 'Create a 3-sentence silly story', 'fun', 90, ARRAY['creativity', 'storytelling', 'imagination'], 2, 'fun'),
('Kahani banao', '3 sentence ki ek funny kahani banao', 'fun', 90, ARRAY['creativity', 'storytelling', 'hinglish'], 2, 'fun'),
('Play rock-paper-scissors', 'Play 3 rounds of rock-paper-scissors', 'fun', 30, ARRAY['game', 'quick', 'fun'], 1, 'fun'),
('Compliment yourself', 'Give yourself 3 funny compliments', 'fun', 45, ARRAY['humor', 'self-love', 'positive'], 1, 'fun'),
('Tareef karo', 'Apne aap ko 3 funny tareef do', 'fun', 45, ARRAY['humor', 'self-love', 'hinglish'], 1, 'fun'),
('Make animal sounds', 'Imitate 5 different animal sounds', 'fun', 45, ARRAY['silly', 'sounds', 'humor'], 1, 'fun'),
('Play memory game', 'Play a quick memory matching game', 'fun', 90, ARRAY['memory', 'game', 'brain'], 2, 'fun'),
('Memory game khelo', 'Ek quick memory matching game khelo', 'fun', 90, ARRAY['memory', 'game', 'hinglish'], 2, 'fun'),
('Do victory dance', 'Do a silly victory dance', 'fun', 30, ARRAY['dance', 'celebration', 'silly'], 1, 'fun'),
('Create emoji story', 'Tell a story using only 10 emojis', 'fun', 60, ARRAY['creativity', 'emojis', 'storytelling'], 2, 'fun'),
('Emoji story banao', '10 emojis use karke ek story banao', 'fun', 60, ARRAY['creativity', 'emojis', 'hinglish'], 2, 'fun'),
('Play would you rather', 'Think of 3 would you rather questions', 'fun', 75, ARRAY['game', 'thinking', 'fun'], 1, 'fun'),
('Whistle a tune', 'Try to whistle your favorite tune', 'fun', 45, ARRAY['music', 'whistling', 'fun'], 1, 'fun'),
('Tune whistle karo', 'Apni favorite tune whistle karne ki koshish karo', 'fun', 45, ARRAY['music', 'whistling', 'hinglish'], 1, 'fun'),
('Make paper airplane', 'Fold and fly a paper airplane', 'fun', 90, ARRAY['craft', 'play', 'creativity'], 1, 'fun'),
('Play tic-tac-toe', 'Play one game of tic-tac-toe', 'fun', 60, ARRAY['game', 'strategy', 'fun'], 1, 'fun'),
('Tic-tac-toe khelo', 'Ek game tic-tac-toe khelo', 'fun', 60, ARRAY['game', 'strategy', 'hinglish'], 1, 'fun'),
('Do tongue twister', 'Try saying a tongue twister 3 times fast', 'fun', 45, ARRAY['language', 'challenge', 'fun'], 2, 'fun'),
('Invent new word', 'Make up a new word and its definition', 'fun', 60, ARRAY['creativity', 'language', 'imagination'], 2, 'fun');

-- SKILL CATEGORY (35 tasks)
INSERT INTO tasks (title, description, category, duration_seconds, tags, difficulty, type) VALUES
('Practice handwriting', 'Write one sentence in your best handwriting', 'skill', 60, ARRAY['writing', 'handwriting', 'practice'], 1, 'skill'),
('Handwriting practice', 'Ek sentence apni best handwriting mein likho', 'skill', 60, ARRAY['writing', 'handwriting', 'hinglish'], 1, 'skill'),
('Learn origami fold', 'Learn one basic origami fold', 'skill', 120, ARRAY['origami', 'craft', 'learning'], 2, 'skill'),
('Practice knot tying', 'Practice tying one useful knot', 'skill', 90, ARRAY['knots', 'practical', 'skill'], 2, 'skill'),
('Knot banana seekho', 'Ek useful knot banana practice karo', 'skill', 90, ARRAY['knots', 'practical', 'hinglish'], 2, 'skill'),
('Improve posture', 'Practice sitting with correct posture for 1 minute', 'skill', 60, ARRAY['posture', 'health', 'habit'], 1, 'skill'),
('Practice signature', 'Practice writing your signature 5 times', 'skill', 45, ARRAY['signature', 'writing', 'practice'], 1, 'skill'),
('Signature practice', 'Apna signature 5 baar practice karo', 'skill', 45, ARRAY['signature', 'writing', 'hinglish'], 1, 'skill'),
('Learn phone feature', 'Learn one new feature on your phone', 'skill', 90, ARRAY['technology', 'phone', 'learning'], 2, 'skill'),
('Practice estimation', 'Estimate 3 measurements then check accuracy', 'skill', 75, ARRAY['estimation', 'math', 'practical'], 2, 'skill'),
('Andaza lagao', '3 measurements ka andaza lagao aur check karo', 'skill', 75, ARRAY['estimation', 'math', 'hinglish'], 2, 'skill'),
('Improve grip strength', 'Squeeze a stress ball or make fists 20 times', 'skill', 45, ARRAY['strength', 'hands', 'exercise'], 2, 'skill'),
('Practice balance', 'Stand on one foot for 30 seconds each', 'skill', 60, ARRAY['balance', 'stability', 'practice'], 2, 'skill'),
('Balance practice', 'Ek-ek pair par 30 second khade raho', 'skill', 60, ARRAY['balance', 'stability', 'hinglish'], 2, 'skill'),
('Learn Excel shortcut', 'Learn one Excel or spreadsheet shortcut', 'skill', 75, ARRAY['excel', 'productivity', 'computer'], 2, 'skill'),
('Practice speed reading', 'Practice speed reading one paragraph', 'skill', 90, ARRAY['reading', 'speed', 'practice'], 3, 'skill'),
('Speed reading karo', 'Ek paragraph ko jaldi padhne ki practice karo', 'skill', 90, ARRAY['reading', 'speed', 'hinglish'], 3, 'skill'),
('Improve listening', 'Practice active listening to a short audio', 'skill', 120, ARRAY['listening', 'communication', 'practice'], 2, 'skill'),
('Practice eye contact', 'Practice maintaining eye contact in mirror', 'skill', 60, ARRAY['communication', 'confidence', 'practice'], 2, 'skill'),
('Eye contact practice', 'Mirror mein eye contact maintain karne ki practice', 'skill', 60, ARRAY['communication', 'confidence', 'hinglish'], 2, 'skill'),
('Learn cooking tip', 'Learn one quick cooking tip or technique', 'skill', 75, ARRAY['cooking', 'food', 'learning'], 1, 'skill'),
('Practice public speaking', 'Practice speaking clearly for 30 seconds', 'skill', 30, ARRAY['speaking', 'communication', 'confidence'], 2, 'skill'),
('Speaking practice', '30 second tak clearly bolne ki practice karo', 'skill', 30, ARRAY['speaking', 'communication', 'hinglish'], 2, 'skill'),
('Improve organization', 'Organize one small area of your workspace', 'skill', 120, ARRAY['organization', 'productivity', 'tidying'], 2, 'skill'),
('Practice time estimation', 'Estimate how long a task will take', 'skill', 45, ARRAY['time-management', 'estimation', 'planning'], 2, 'skill'),
('Time estimate karo', 'Kisi task mein kitna time lagega, estimate karo', 'skill', 45, ARRAY['time-management', 'estimation', 'hinglish'], 2, 'skill'),
('Learn photo editing', 'Learn one basic photo editing technique', 'skill', 120, ARRAY['photography', 'editing', 'creative'], 3, 'skill'),
('Practice negotiation', 'Think through one negotiation scenario', 'skill', 90, ARRAY['negotiation', 'communication', 'thinking'], 3, 'skill'),
('Negotiation soch', 'Ek negotiation scenario ke baare mein socho', 'skill', 90, ARRAY['negotiation', 'communication', 'hinglish'], 3, 'skill'),
('Improve email writing', 'Draft one clear and concise email', 'skill', 120, ARRAY['writing', 'email', 'communication'], 2, 'skill'),
('Practice decision making', 'Make one small decision quickly', 'skill', 30, ARRAY['decision-making', 'thinking', 'practice'], 2, 'skill'),
('Faisla karo', 'Ek chhota faisla jaldi se karo', 'skill', 30, ARRAY['decision-making', 'thinking', 'hinglish'], 2, 'skill'),
('Learn first aid tip', 'Learn one basic first aid technique', 'skill', 90, ARRAY['first-aid', 'health', 'safety'], 2, 'skill'),
('Practice mindful breathing', 'Practice box breathing technique', 'skill', 90, ARRAY['breathing', 'mindfulness', 'technique'], 2, 'skill'),
('Box breathing karo', 'Box breathing technique practice karo', 'skill', 90, ARRAY['breathing', 'mindfulness', 'hinglish'], 2, 'skill'),
('Improve note-taking', 'Practice taking notes in bullet points', 'skill', 90, ARRAY['notes', 'organization', 'learning'], 2, 'skill'),
('Learn body language', 'Learn about one body language cue', 'skill', 75, ARRAY['body-language', 'communication', 'learning'], 2, 'skill');

-- CHALLENGE CATEGORY (35 tasks)
INSERT INTO tasks (title, description, category, duration_seconds, tags, difficulty, type) VALUES
('No phone challenge', 'Go 2 minutes without checking your phone', 'challenge', 120, ARRAY['digital-detox', 'mindfulness', 'discipline'], 2, 'challenge'),
('Phone mat dekho', '2 minute tak phone check mat karo', 'challenge', 120, ARRAY['digital-detox', 'mindfulness', 'hinglish'], 2, 'challenge'),
('Perfect posture challenge', 'Maintain perfect posture for 1 minute', 'challenge', 60, ARRAY['posture', 'discipline', 'health'], 2, 'challenge'),
('No complaining challenge', 'Go 2 minutes without complaining', 'challenge', 120, ARRAY['positivity', 'mindset', 'discipline'], 2, 'challenge'),
('Shikayat mat karo', '2 minute tak koi shikayat mat karo', 'challenge', 120, ARRAY['positivity', 'mindset', 'hinglish'], 2, 'challenge'),
('Speed challenge', 'Write alphabet as fast as possible', 'challenge', 45, ARRAY['speed', 'writing', 'challenge'], 2, 'challenge'),
('Hold breath challenge', 'Hold your breath for 30 seconds safely', 'challenge', 30, ARRAY['breathing', 'endurance', 'challenge'], 3, 'challenge'),
('Saans roko', '30 second tak safely saans roko', 'challenge', 30, ARRAY['breathing', 'endurance', 'hinglish'], 3, 'challenge'),
('No sugar challenge', 'Commit to no added sugar for next 2 hours', 'challenge', 30, ARRAY['health', 'discipline', 'nutrition'], 2, 'challenge'),
('Silence challenge', 'Stay completely silent for 1 minute', 'challenge', 60, ARRAY['silence', 'mindfulness', 'discipline'], 1, 'challenge'),
('Chup raho', '1 minute tak bilkul chup raho', 'challenge', 60, ARRAY['silence', 'mindfulness', 'hinglish'], 1, 'challenge'),
('No sitting challenge', 'Stand for the next 5 minutes', 'challenge', 30, ARRAY['movement', 'health', 'discipline'], 2, 'challenge'),
('Memory challenge', 'Memorize 7 random items in order', 'challenge', 90, ARRAY['memory', 'brain', 'challenge'], 3, 'challenge'),
('Yaad karo challenge', '7 random cheezein order mein yaad karo', 'challenge', 90, ARRAY['memory', 'brain', 'hinglish'], 3, 'challenge'),
('One hand challenge', 'Do a simple task using only one hand', 'challenge', 90, ARRAY['dexterity', 'challenge', 'skill'], 3, 'challenge'),
('No negative thoughts', 'Replace negative thoughts with positive for 2 min', 'challenge', 120, ARRAY['positivity', 'mindset', 'mental-health'], 3, 'challenge'),
('Positive socho', '2 minute tak sirf positive thoughts rakho', 'challenge', 120, ARRAY['positivity', 'mindset', 'hinglish'], 3, 'challenge'),
('Speed reading challenge', 'Read as many words as possible in 1 minute', 'challenge', 60, ARRAY['reading', 'speed', 'challenge'], 3, 'challenge'),
('No excuses challenge', 'Take responsibility without making excuses', 'challenge', 45, ARRAY['accountability', 'growth', 'mindset'], 2, 'challenge'),
('Bahane mat banao', 'Koi bahana banaye bina responsibility lo', 'challenge', 45, ARRAY['accountability', 'growth', 'hinglish'], 2, 'challenge'),
('Gratitude challenge', 'Find 5 things to be grateful for right now', 'challenge', 90, ARRAY['gratitude', 'positivity', 'mindfulness'], 2, 'challenge'),
('Wall sit challenge', 'Do a wall sit for 30 seconds', 'challenge', 30, ARRAY['strength', 'endurance', 'legs'], 4, 'challenge'),
('Wall sit karo', '30 second tak wall sit position hold karo', 'challenge', 30, ARRAY['strength', 'endurance', 'hinglish'], 4, 'challenge'),
('No multitasking', 'Focus on only one task for 2 minutes', 'challenge', 120, ARRAY['focus', 'productivity', 'mindfulness'], 2, 'challenge'),
('Backwards challenge', 'Say alphabet backwards as fast as you can', 'challenge', 60, ARRAY['brain', 'challenge', 'memory'], 3, 'challenge'),
('Ulta bolo', 'Alphabet ko ulta jitna jaldi ho sake bolo', 'challenge', 60, ARRAY['brain', 'challenge', 'hinglish'], 3, 'challenge'),
('No screen challenge', 'Avoid all screens for next 5 minutes', 'challenge', 30, ARRAY['digital-detox', 'discipline', 'health'], 2, 'challenge'),
('Patience challenge', 'Wait patiently for 1 minute doing nothing', 'challenge', 60, ARRAY['patience', 'mindfulness', 'discipline'], 2, 'challenge'),
('Sabr rakho', '1 minute tak kuch kiye bina patiently wait karo', 'challenge', 60, ARRAY['patience', 'mindfulness', 'hinglish'], 2, 'challenge'),
('No fidgeting challenge', 'Sit completely still for 1 minute', 'challenge', 60, ARRAY['stillness', 'discipline', 'mindfulness'], 2, 'challenge'),
('Smile challenge', 'Smile continuously for 1 minute', 'challenge', 60, ARRAY['positivity', 'mood', 'challenge'], 1, 'challenge'),
('Muskurate raho', '1 minute tak continuously muskurate raho', 'challenge', 60, ARRAY['positivity', 'mood', 'hinglish'], 1, 'challenge'),
('No interrupting', 'Listen to someone without interrupting', 'challenge', 120, ARRAY['listening', 'communication', 'respect'], 2, 'challenge'),
('Cold water challenge', 'Splash cold water on face and embrace it', 'challenge', 30, ARRAY['cold', 'energy', 'challenge'], 2, 'challenge'),
('Thanda pani challenge', 'Apne face par thanda pani dalo aur embrace karo', 'challenge', 30, ARRAY['cold', 'energy', 'hinglish'], 2, 'challenge'),
('No snooze challenge', 'Commit to not hitting snooze tomorrow', 'challenge', 30, ARRAY['discipline', 'morning', 'habit'], 2, 'challenge'),
('Gratitude letter', 'Write 3 sentences thanking someone mentally', 'challenge', 90, ARRAY['gratitude', 'kindness', 'writing'], 2, 'challenge');

-- Add comment about seed data
COMMENT ON TABLE tasks IS 'Seeded with 210 tasks (35 per category) with English and Hinglish descriptions';
